Total kalkulacije
RAF-SI-2021/Racunovodstvo-Back pull request #139
Opened 2022-05-08 22:11 UTC by aleksadacic

2022-05-11 14:31 UTC, gojkovicmatija99 commented on nabavka/src/main/java/raf/si/racunovodstvo/nabavka/controllers/KalkulacijaController.java
> +    public ResponseEntity<?> getTotalKalkulacije(
Sta ce da se desi ako je search prazan string?

2022-05-13 22:11 UTC, borisstojanovic approved these changes

2022-05-13 22:15 UTC, borisstojanovic requested changes
Ako mozes, samo razresi konflikte, ostalo je sve ok.

2022-05-13 22:21 UTC, gojkovicmatija99 approved these changes

2022-05-14 23:18 UTC, borisstojanovic approved these changes

2022-05-16 18:24 UTC, merged