#19 CRUD kontne grupe
RAF-SI-2021/Racunovodstvo-Back pull request #45
Opened 2022-03-27 09:43 UTC by aleksadacic

2022-03-28 09:18 UTC, gojkovicmatija99 commented on src/main/java/rs/raf/demo/utils/Utils.java
> +    }
Da li mozemo da izbegnemo ovo koriscenjem StringUtils iz paketa `org.apache.commons.lang3.StringUtils`

2022-03-28 09:18 UTC, gojkovicmatija99 commented on src/main/java/rs/raf/demo/controllers/KontnaGrupaController.java
> +    public ResponseEntity<?> getKontneGrupe(@RequestParam("sort") String sort) {
Da li mozemo da izbegnemo ovo splitovanje ako stavimo `@RequestParam(defaultValue="brojKonta") String[] sort`

2022-03-28 09:18 UTC, gojkovicmatija99 commented on src/main/java/rs/raf/demo/controllers/KontnaGrupaController.java
> +                return ResponseEntity.ok(kontnaGrupaService.findAllSorted(params));
Takodje, ako imamo u potpisu metode `(defaultValue="brojKonta")`, mozemo imati samo jednu metodu `findAll(params)`. Trenutno `findAll()` ti je isto kao `findAllSorted(params)` po brojKonta

2022-03-28 09:18 UTC, gojkovicmatija99 commented on src/main/java/rs/raf/demo/services/impl/KontnaGrupaService.java
> +    }
Ostavit ovu jednu metodu i preimenovati u `findAll`

2022-03-28 20:12 UTC, mstosic99 requested changes

2022-03-29 09:04 UTC, aleksadacic commented on src/main/java/rs/raf/demo/controllers/KontnaGrupaController.java
> +            return ResponseEntity.ok(kontnaGrupaService.findAll(sort));
u pravu si, to mi je bilo privremeno resenje za nesto, ali sam posle one refaktorizacije zaboravio i to da izmenim

2022-04-01 10:41 UTC, merged